<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><title>Site Checkpoint Scan Report</title>
<style>
@page{size:A4 landscape;margin:12px 16px 24px}*{box-sizing:border-box}body{margin:0;font-family:DejaVu Sans,sans-serif;color:#182236;font-size:7.5px}.header{background:#201b59;color:#fff;padding:9px 14px;border-radius:5px}.header-table,.summary-table,.info-table{width:100%;border-collapse:collapse}.brand{font-size:14px;font-weight:bold;letter-spacing:.5px}.report-title{font-size:14px;font-weight:bold;text-align:right}.report-subtitle{color:#c9c5ff;text-align:right;margin-top:2px;font-size:6.5px}.accent{height:2px;width:65px;background:#7c3aed;margin-top:4px}.summary{margin:6px 0}.summary td{width:16.66%;padding:5px;text-align:center;background:#f5f3ff;border-right:2px solid #fff}.metric{display:block;font-size:12px;font-weight:bold;color:#312e81}.metric-label{display:block;margin-top:1px;color:#697386;font-size:5.8px;text-transform:uppercase}.section-title{margin:7px 0 4px;padding:4px 7px;color:#fff;background:#312e81;font-size:8px;font-weight:bold;border-radius:3px}.info-table td{width:25%;padding:4px 6px;border:1px solid #e5e7eb;vertical-align:top}.label{display:block;color:#7b8494;font-size:5.5px;text-transform:uppercase;margin-bottom:1px}.value{font-weight:bold;color:#172033}.items{width:100%;border-collapse:collapse;table-layout:fixed}.items th{background:#ede9fe;color:#312e81;padding:5px 3px;font-size:5.8px;text-transform:uppercase;border:1px solid #ddd6fe}.items td{padding:5px 4px;border:1px solid #e5e7eb;vertical-align:middle}.items tr:nth-child(even) td{background:#fafafa}.center{text-align:center}.tag{color:#312e81;font-weight:bold}.status{display:inline-block;color:#fff;background:#059669;font-weight:bold;padding:2px 6px;border-radius:7px;font-size:5.8px}.image-link{display:inline-block;padding:2px 6px;color:#fff;background:#7c3aed;border-radius:5px;font-size:5.5px;font-weight:bold;text-decoration:none}.empty{color:#9ca3af;font-style:italic;text-align:center}.footer{position:fixed;bottom:-17px;left:0;right:0;color:#7b8494;font-size:5.8px;border-top:1px solid #e5e7eb;padding-top:4px}.footer-right{float:right}
</style></head><body>
<div class="header"><table class="header-table"><tr><td><div class="brand">ELITE SECURITY</div><div class="accent"></div></td><td><div class="report-title">SITE CHECKPOINT SCAN REPORT</div><div class="report-subtitle">Report #SSR-{{ str_pad($site->id, 6, '0', STR_PAD_LEFT) }} | Generated {{ now()->format('d M Y, h:i A') }}</div></td></tr></table></div>
<table class="summary-table summary"><tr>
<td><span class="metric">{{ $summary['total_scans'] }}</span><span class="metric-label">Total Scans</span></td><td><span class="metric">{{ $summary['site_checkpoints'] }}</span><span class="metric-label">Site Checkpoints</span></td><td><span class="metric">{{ $summary['checkpoints_scanned'] }}</span><span class="metric-label">Checkpoints Scanned</span></td><td><span class="metric">{{ $summary['guards'] }}</span><span class="metric-label">Guards</span></td><td><span class="metric">{{ $summary['days'] }}</span><span class="metric-label">Active Days</span></td><td><span class="metric">{{ $summary['evidence'] }}</span><span class="metric-label">Evidence Images</span></td>
</tr></table>
<div class="section-title">Site and Report Details</div>
<table class="info-table"><tr><td><span class="label">Company</span><span class="value">{{ $site->company?->name ?? 'N/A' }}</span></td><td><span class="label">Site</span><span class="value">{{ $site->name }}</span></td><td><span class="label">Site Address</span><span class="value">{{ $site->address ?: trim(($site->city ?? '') . ', ' . ($site->country ?? ''), ', ') ?: 'N/A' }}</span></td><td><span class="label">Selected User</span><span class="value">{{ $selectedUser?->name ?? 'All Users' }}</span></td></tr><tr><td><span class="label">Start Date</span><span class="value">{{ \Carbon\Carbon::parse($filters['start_date'])->format('l, d M Y') }}</span></td><td><span class="label">End Date</span><span class="value">{{ \Carbon\Carbon::parse($filters['end_date'])->format('l, d M Y') }}</span></td><td><span class="label">Search Filter</span><span class="value">{{ $filters['search'] ?? 'None' }}</span></td><td><span class="label">Report Status</span><span class="value">Final / Generated</span></td></tr></table>
<div class="section-title">Checkpoint Scan Performance</div>
<table class="items"><thead><tr><th style="width:5%">#</th><th style="width:12%">Date</th><th style="width:12%">Scan Time</th><th style="width:18%">Guard / User</th><th style="width:22%">Checkpoint / Tag</th><th style="width:16%">Tag UID</th><th style="width:15%">Evidence / Status</th></tr></thead><tbody>
@forelse($scans as $scan)<tr><td class="center">{{ $loop->iteration }}</td><td class="center">{{ $scan->date?->format('d M Y') ?? 'N/A' }}</td><td class="center">{{ $scan->time ? \Carbon\Carbon::parse($scan->time)->format('h:i:s A') : 'N/A' }}</td><td>{{ $scan->user?->name ?? 'N/A' }}</td><td class="tag">{{ $scan->nfcTag?->name ?? 'Unknown Tag' }}</td><td class="center">{{ $scan->nfcTag?->uid ?? 'N/A' }}</td><td class="center">@if($scan->image) @php $imageUrl = \Illuminate\Support\Str::startsWith($scan->image, ['http://', 'https://']) ? $scan->image : asset('storage/' . ltrim($scan->image, '/')); @endphp <a class="image-link" href="{{ $imageUrl }}">View Image</a> @else <span class="status">Scanned</span> @endif</td></tr>@empty<tr><td colspan="7" class="empty">No checkpoint scans found for the selected filters.</td></tr>@endforelse
</tbody></table>
<div class="footer">Confidential operational report - Elite Security<span class="footer-right">Site #{{ $site->id }} | {{ $site->name }}</span></div>
<script type="text/php">if(isset($pdf)){$pdf->page_text(735,570,"Page {PAGE_NUM} of {PAGE_COUNT}",null,7,array(.45,.49,.58));}</script>
</body></html>
