<?php

return [

    'currency_map' => [
        'Pakistan'              => 'PKR',
        'United Kingdom'        => 'GBP',
        'Germany'               => 'EUR',
        'France'                => 'EUR',
        'Italy'                 => 'EUR',
        'Spain'                 => 'EUR',
        'Netherlands'           => 'EUR',
        'Belgium'               => 'EUR',
        'Austria'               => 'EUR',
        'Portugal'              => 'EUR',
        'Ireland'               => 'EUR',
        'Finland'               => 'EUR',
        'Sweden'                => 'SEK',
        'Norway'                => 'NOK',
        'Denmark'               => 'DKK',
        'Switzerland'           => 'CHF',
        'United States'         => 'USD',
        'Canada'                => 'CAD',
        'Australia'             => 'AUD',
        'New Zealand'           => 'NZD',
        'India'                 => 'INR',
        'China'                 => 'CNY',
        'Japan'                 => 'JPY',
        'South Korea'           => 'KRW',
        'Turkey'                => 'TRY',
        'Russia'                => 'RUB',
        'Brazil'                => 'BRL',
        'South Africa'          => 'ZAR',
        'Saudi Arabia'          => 'SAR',
        'United Arab Emirates'  => 'AED',
        'Malaysia'              => 'MYR',
        'Singapore'             => 'SGD',
        'Bangladesh'            => 'BDT',
        'Greece'                => 'EUR',
        'Poland'                => 'PLN',
        'Czech Republic'        => 'CZK',
        'Hungary'               => 'HUF',
        'Romania'               => 'RON',
    ],

    'languages' => [
        'Multiple',
        'English',
        'German',
        'French',
        'Spanish',
        'Italian',
        'Dutch',
        'Portuguese',
        'Swedish',
        'Norwegian',
        'Danish',
        'Finnish',
        'Polish',
        'Czech',
        'Slovak',
        'Hungarian',
        'Romanian',
        'Bulgarian',
        'Croatian',
        'Serbian',
        'Russian',
        'Arabic',
        'Chinese',
        'Japanese',
        'Korean',
        'Turkish',
        'Greek',
        'Hebrew',
        'Urdu',
        'Hindi',
        'Bengali',
    ],

];
