<?php

return [
    'categories' => [
        'Agriculture & Food Studies' => [
            'Agriculture',
            'Agricultural Economics',
            'Agricultural Engineering',
            'Agronomy',
            'Animal Behaviour & Welfare',
            'Animal Science',
            'Aquaculture',
            'Fisheries Management',
            'Food Safety & Quality',
            'Food Science',
            'Food Technology',
            'Forestry',
            'Horticulture and Crop Science',
            'Landscape Architecture',
            'Marine Biology',
            'Marine Science',
            'Pest Management',
            'Plant Biology & Pathology',
            'Rural Development',
            'Soil & Land Management',
            'Sustainable Agriculture',
            'Veterinary Science',
            'Wildlife Management',
        ],
        'Applied & Professional Studies' => [
            'Aviation Studies',
            'Emergency & Disaster Management',
            'Family & Consumer Science',
            'Fashion, Textiles and Luxury Goods',
            'Food Science',
            'Forensic Science',
            'Library Science',
            'Military Science',
            'Museum Studies',
            'Real Estate & Property Management',
            'Social Work',
            'Transport',
        ],
        'Art, Design & Creative Fields' => [
            'Architecture',
            'Art and Craft',
            'Art History',
            'Ceramics and Sculpture',
            'Dance',
            'Design',
            'Drama',
            'Fashion Design',
            'Film Studies',
            'Fine Arts',
            'Graphic Design',
            'Industrial Design',
            'Interior Design',
            'Landscape Architecture',
            'Music',
            'Music Composition',
            'Music Performance',
            'Musicology',
            'Painting & Drawing',
            'Photography',
            'Urban Planning',
            'Visual Arts',
        ],
        'Business & Management' => [
            'Accounting',
            'Actuarial Science',
            'Advertising',
            'Agribusiness',
            'Auditing',
            'Banking',
            'Business Administration',
            'Business Intelligence',
            'Commerce',
            'Construction Management',
            'Corporate Communication',
            'Corporate Social Responsibility',
            'Digital Marketing',
            'Digital Media',
            'Engineering Management',
            'Entrepreneurship',
            'Executive MBA',
            'Fashion Management',
            'Finance',
            'Financial Management',
            'Financial Technology',
            'Forensic Accounting',
            'Human Resource Management',
            'Innovation Management',
            'Insurance',
            'International Business',
            'Investment',
            'IT Management',
            'Leadership',
            'Management of Creative Industries',
            'Management Studies',
            'Marketing',
            'Marketing Management',
            'Master in Business Administration (MBA)',
            'Master in Management (MIM)',
            'Operations and Quality Management',
            'Project Management',
            'Public Administration',
            'Retail Management',
            'Risk Management',
            'Strategic Management',
            'Supply Chain Management & Logistics',
            'Taxation',
            'Transport Management',
        ],
        'Computing & Digital Technologies' => [
            'Animation',
            'Artificial Intelligence',
            'Augmented Reality & Virtual Reality',
            'Blockchain Technology',
            'Business Information Systems',
            'Cloud Computing',
            'Computer Engineering',
            'Computer Networks',
            'Computer Sciences',
            'Computer Vision',
            'Cyber Security',
            'Data Analytics',
            'Data Science & Big Data',
            'Database Management',
            'Deep Learning',
            'Digital Forensics',
            'Distributed Systems',
            'Embedded Systems',
            'Game Design',
            'Geographical Information Systems (GIS)',
            'Health Informatics',
            'Human Computer Interaction',
            'Information Systems',
            'Information Technology (IT)',
            'Internet of Things (IoT)',
            'IT Project Management',
            'Machine Learning',
            'Mobile Application Development',
            'Natural Language Processing',
            'Network Security',
            'Operating Systems',
            'Quantum Computing',
            'Robotics',
            'Software Engineering',
            'Software Testing & Quality Assurance',
            'Systems Architecture',
            'User Experience Design',
            'Web Development',
            'Web Technologies & Cloud Computing',
        ],
        'Education & Teaching Studies' => [
            'Adult Education',
            'Art Education',
            'Coaching',
            'Early Childhood Education',
            'Education',
            'Educational Leadership',
            'Educational Psychology',
            'Educational Research',
            'Health Education',
            'Higher Education',
            'Instructional Design',
            'Literacy Education',
            'Primary Education',
            'School Counselling',
            'Secondary Education',
            'Special Education',
            'STEM Education',
            'Teaching',
            'Teaching English as a Foreign Language',
        ],
        'Engineering & Technical Fields' => [
            'Aerospace Engineering',
            'Automotive Engineering',
            'Bio & Biomedical Engineering',
            'Chemical Engineering',
            'Civil Engineering & Construction',
            'Communications Engineering',
            'Electrical Engineering',
            'Electronics & Embedded Technology',
            'Energy Engineering',
            'Environmental Engineering',
            'General Engineering & Technology',
            'Industrial & Systems Engineering',
            'Marine Engineering',
            'Materials Science Studies',
            'Mechanical Engineering',
            'Mechatronics',
            'Mining, Oil & Gas Studies',
            'Nuclear Engineering',
            'Production and Manufacturing Engineering',
            'Robotics',
            'Sound Engineering',
            'Structural Engineering',
            'Sustainable Energy',
            'Transportation Engineering',
        ],
        'Environmental & Earth Sciences' => [
            'Biodiversity & Conservation',
            'Climate Studies & Meteorology',
            'Earth Sciences',
            'Ecology',
            'Environmental Economics & Policy',
            'Environmental Management',
            'Environmental Sciences',
            'Geology',
            'Hydrology & Water Management',
            'Natural Resource Management',
            'Ocean & Marine Sciences',
            'Remote Sensing & GIS',
            'Renewable Energy & Sustainability',
            'Soil Science',
            'Sustainable Development',
            'Toxicology',
            'Urban & Regional Planning',
        ],
        'Hospitality, Tourism & Sports' => [
            'Culinary Arts',
            'Event Management',
            'Food & Beverage Management',
            'Golf Management',
            'Hospitality Management',
            'Hotel Management',
            'Leisure & Recreation Management',
            'Resort & Club Management',
            'Sport and Exercise Science',
            'Sports Coaching',
            'Sports Management',
            'Sports Marketing',
            'Tourism & Leisure',
            'Travel & Tourism Management',
            'Wellness & Spa Management',
        ],
        'Humanities & Cultural Studies' => [
            'Ancient History',
            'Anthropology',
            'Archaeology',
            'Christian Studies',
            'Classics',
            'Creative Writing',
            'Cultural Studies',
            'ESL',
            'Ethics',
            'General Studies',
            'History',
            'Islamic Studies',
            'Language Studies',
            'Liberal Arts',
            'Linguistics',
            'Literature',
            'Modern History',
            'Philosophy',
            'Theology and Religious Studies',
        ],
        'Media, Communication & Journalism' => [
            'Broadcasting & Radio',
            'Journalism',
            'Media Management',
            'Media Studies & Mass Media',
            'Photography & Photojournalism',
            'Public Relations',
            'Publishing',
            'Translation & Interpreting',
        ],
        'Law & Legal Studies' => [
            'Business Law',
            'Civil & Private Law',
            'Commercial & Contract Law',
            'Criminal Justice',
            'Criminal Law',
            'European Law',
            'Human Rights Law',
            'International Law',
            'Legal Studies',
            'Master of Laws (LLM)',
            'Patent & Intellectual Property Law',
            'Public Law',
        ],
        'Health, Medicine & Life Sciences' => [
            'Biomedical Science',
            'Clinical Psychology',
            'Complementary & Alternative Medicine',
            'Dentistry',
            'Epidemiology',
            'Gerontology',
            'Health Sciences',
            'Healthcare Administration',
            'Immunology',
            'Kinesiology',
            'Medical Imaging',
            'Medicine',
            'Midwifery',
            'Nursing',
            'Nutrition & Dietetics',
            'Occupational Health and Safety',
            'Occupational Therapy',
            'Optometry',
            'Pathology',
            'Pharmacy',
            'Physiology',
            'Physiotherapy',
            'Prosthetics and Orthotics',
            'Public Health',
            'Speech Pathology',
            'Veterinary Medicine',
        ],
        'Science, Mathematics & Analytics' => [
            'Anatomy',
            'Applied Mathematics',
            'Astronomy & Space Sciences',
            'Biochemistry',
            'Bioinformatics & Biostatistics',
            'Biology',
            'Biotechnology',
            'Botany',
            'Chemistry',
            'Computational Mathematics',
            'Financial Mathematics',
            'Genetics',
            'Mathematics',
            'Microbiology',
            'Molecular Sciences',
            'Nanoscience and Nanotechnology',
            'Natural Sciences',
            'Neuroscience',
            'Oceanography',
            'Operations Research',
            'Pharmacology',
            'Physics',
            'Statistics',
            'Zoology',
        ],
        'Social & Behavioral Sciences' => [
            'African Studies',
            'American and Australasian Studies',
            'Anthropology',
            'Archaeology',
            'Area & Cultural Studies',
            'Art Therapy',
            'Asian Studies',
            'British Studies',
            'Childhood Studies',
            'Cognitive Science',
            'Communication Studies',
            'Community Development',
            'Counselling Psychology',
            'Criminology',
            'Developmental Psychology',
            'Diplomacy',
            'Econometrics',
            'Economics',
            'Ethnic Studies',
            'European Studies',
            'Forensic Psychology',
            'French Studies',
            'Gender & Sexuality Studies',
            'Geography',
            'German and Scandinavian Studies',
            'Iberian Studies',
            'International Development',
            'International Relations',
            'Italian Studies',
            'Middle Eastern Studies',
            'Organisational Behaviour',
            'Political Science',
            'Psychology',
            'Public Policy',
            'Slavic Studies',
            'Social Policy',
            'Social Psychology',
            'Sociology',
            'Terrorism & Security',
        ],
    ],
];
