@if($type == 'general')
    @include('admin.unified-reports.tables.general')
@elseif($type == 'incident')
    @include('admin.unified-reports.tables.incident')
@elseif($type == 'disciplinary')
    @include('admin.unified-reports.tables.disciplinary')
@elseif($type == 'daily-shift')
    @include('admin.unified-reports.tables.daily-shift')
@elseif($type == 'assessments')
    @include('admin.unified-reports.tables.assessments')
@elseif($type == 'vehicle-checklist')
    @include('admin.unified-reports.tables.vehicle-checklist')
@elseif($type == 'fire-watch')
    @include('admin.unified-reports.tables.fire-watch')
@elseif($type == 'shift-adjustment')
    @include('admin.unified-reports.tables.shift-adjustment')
@endif
